server:
  port: 8011  # 端口
spring:
  application:
    name: CLOUD-RIBBON-MESSAGESYSTEM # 项目名称
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # 服务注册中心地址
  instance:
    preferIpAddress: true
    
# log4j2 config
logging :
  config : classpath:log4j2.xml