server:
  port: 8600   
#数据库相关配置
spring:
  datasource:
    url: jdbc:mysql://175.6.73.138:3406/iot_master_test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root