spring:
  application:
    name: microservice-api-gateway
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true 
    name: base
    #url: jdbc:mysql://127.0.0.1:3306/gateway_api_define
    url: jdbc:mysql://175.6.65.239:3170/iotcloud
    username: tuping
    password: 123456
    initialSize: 5
    minIdle: 5
    maxIdle: 20
    maxActive: 20
    maxWait: 60000 
    timeBetweenEvictionRunsMillis: 60000 
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
server:
  port: 8050
eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignored-services: microservice-provider-user                        # 需要忽视的服务(配置后将不会被路由)
  routes:
    api-a:                                                            # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /api-a/**                                             # 想要映射到的路径
      service-id: CLOUD-RIBBON-MESSAGESYSTEM     # Eureka中的serviceId
