node1: 172.16.20.179
node2: 172.16.20.177
server:
  port: 8200
  
spring:
  application: 
    name: zuul-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.20.209:3306/iot_zuul?characterEncoding=utf8&useSSL=false
    username: root
    password: cimr@123  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: com.cimr.boot.model.dialect.FastCustomSQLDialect


eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ipAddress}
  client:
    service-url: 
      defaultZone: http://${node2}:8888/eureka/,http://${node1}:8888/eureka/
zuul: 
  ignored-services: '*'
  host:
    max-total-connections: 1000
    max-per-route-connections: 1000
  routes:     
     client: 
        strip-prefix: true
        path: /client/**
        service-id: client
     out: 
        strip-prefix: true
        path: /out/**
        service-id: out
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000 

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled:false            
ribbon: 
  ConnectTimeout: 3000
  ReadTimeout: 60000


            

       

      
       