server:
  port: 8053
  
# log4j2 config
logging :
  config : classpath:log4j2.xml
  
  
spring:
  application:
    name: MessageSystem
  cloud:
    config:
      profile: dev
      label: master
      discovery:
        enabled: true                                 # 默认false，设为true表示使用注册中心中的configserver配置而不自己配置configserver的uri
        serviceId: microservice-config-server-eureka  # 指定config server在服务发现中的serviceId，默认为：configserver
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    base:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initialize: true 
      name: base
      url: jdbc:mysql://127.0.0.1:3306/messagesystem
      username: root
      password: 123456
      initialSize: 5
      minIdle: 5
      maxIdle: 20
      maxActive: 20
      maxWait: 60000 
      timeBetweenEvictionRunsMillis: 60000 
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
    
  

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/


